【FE課題】Step1
NBshiozawa/dept_design_fe_work01 pull request #1
Opened 2023-11-13 07:47 UTC by NBshiozawa

### Step1

* モックデータを使用して、任意の1冊の情報を表示する

こちらの対応を行いましたので、お手数ですがご確認よろしくお願いします。

### issue
newbeescoltd/nb_study_react/issues/3

2023-11-13 10:30 UTC, NBmaeda requested changes
まずはStep1の最初のコミットお疲れ様です👏
しっかり勉強いただいていることも感じられ、何より綺麗なCSSでのスタイリングで流石だなと感じました🎉

レビュー内容は主に +α 的な内容となっています。
細かい指摘も多いですが今後の学習の基礎になる部分なので、着実に対応していってもらえればと思います。
対応のほどよろしくお願いします🙏

2023-11-13 10:30 UTC, NBmaeda commented on booklog/src/App.tsx
> +          <li className="listitem" key={bookInfo.id}>
この行で指定されている`key`属性ですが、この段階では指定する必要はないです💡
指定してもおそらく問題はないのですが、React側でこの情報を使用する必要がないため指定しなくても良いという感じです。
ただ今後のStepで複数の書籍情報をリストアップする際に必要になってくるので、それを見越しているなら問題ないのでこのレビューは無視してください🙏

ちょうど良いので、Reactにおける`map()`によるループと`key`属性に関して書かれているリソースを紹介します。
https://ja.react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key
`key`の必要性に関してわかりやすく書かれているため、まだ読んだことがなければ是非目を通してください。

2023-11-13 10:30 UTC, NBmaeda commented on booklog/src/App.tsx
> +  const Book = (bookInfo: BookItem): JSX.Element => {
ここの引数名`bookInfo`は間違いではないのですが、慣習的に`props`とされることが多いです。
第三者がパッと見てJSXを返すコンポーネントだと判断しやすい、プロジェクト全体の統一性を担保しやすい、などのメリットが考えられるためここはできるだけ慣習に従う方が良いと思います。

一方で引数の箇所に関しては、分割代入を使用することも多いです。僕もこれを使用することを推奨しています。
[こちら](https://ja.react.dev/learn/passing-props-to-a-component#step-2-read-props-inside-the-child-component)のStep2に書かれている、以下のような`{}`(カーリーブラケット)を使用した引数の指定の仕方ですね。
```
function Avatar({ person, size }) {
  // person and size are available here
}
```

これを用いることで、一見してどんな引数を扱うかを判断しやすくなったり、コード量を削減できたりなどのメリットが見込めます。
Reactは歴史も長いため色々書き方があってややこしいですが、以下のような視点を持って学習を進めると、より頭に入りやすいかもしれません💡
- 一般的にどのような記述が用いられるか
- その記述はどういったメリットから使用されているか

2023-11-13 10:30 UTC, NBmaeda commented on booklog/src/App.tsx
> +            {bookInfo.volumeInfo.imageLinks && (
他の行も含め、しっかり条件付きレンダリングを使用できていて素晴らしいです👏

2023-11-13 10:30 UTC, NBmaeda commented on booklog/src/App.tsx
> +      <Book id={bookItem[0].id} volumeInfo={bookItem[0].volumeInfo} />
この箇所は[スプレッド構文](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Spread_syntax)を使用することで、より簡潔に書くことができます。

先ほど紹介した[こちら](https://ja.react.dev/learn/passing-props-to-a-component)の公式ドキュメントにも記載があるので、参考にして修正してみてください。
記述が簡潔になることでコード全体の見通しが良くなるため、積極的に使っていきましょう！

2023-11-13 10:30 UTC, NBmaeda commented on booklog/src/App.tsx
> +              <div className="sub-info">
この行ですが`authors`と`publisher`の両方が存在しない場合、不必要な`<div className="sub-info">`のみが出力されてしまいます。
見た目的には問題ないのですがHTMLの文書構造的には望ましくないため、両方が存在しない場合にも対応できるように修正してみてください。

2023-11-17 01:51 UTC, NBshiozawa commented on booklog/src/App.tsx
> +          <li className="listitem" key={bookInfo.id}>
参考ページありがとうございます！
なるほどです。次のステップで`map()`ループを使用する際に指定する感じですね！
`key`属性は削除いたしました🙇‍♀️

2023-11-17 01:53 UTC, NBshiozawa commented on booklog/src/App.tsx
> +  const Book = (bookInfo: BookItem): JSX.Element => {
こちらは分割代入を使用してみました！
確かに、コードがすっきりして感動です（冗長な記述になってるのが気になってました...）
今後の学習についてもアドバイスありがとうございます！留意いたします🫡

2023-11-17 01:55 UTC, NBshiozawa commented on booklog/src/App.tsx
> +              <div className="sub-info">
`authors`、`publisher` のどちらかがあれば表示、のように指定してみました！

2023-11-17 04:07 UTC, NBmaeda approved these changes
Step1お疲れ様でした🎉
修正も反映されていて問題ないと思います！

コメントは +α の情報を記載しておりますので、よければ確認してください。
他の業務もあり大変かと思いますが、引き続きサポートしますので頑張っていきましょう！💪

2023-11-17 04:07 UTC, NBmaeda commented on booklog/src/App.tsx
> +              {(authors || publisher) && (
論理演算子をうまく利用して、条件付きレンダリングができていて良いと思います👏

2023-11-17 04:07 UTC, NBmaeda commented on booklog/src/App.tsx
> +  }: BookItem['volumeInfo']): JSX.Element => {
分割代入を利用できていて良いですね🙆
別の方法としては、`const Book = (props: BookItem)=>...`のように受け取って、以下のような形で分割代入することも可能です。
```
const Book = (props: BookItem): JSX.Element => {
    const { title, authors, description, publisher, imageLinks, previewLink }: BookItem['volumeInfo'] = props.volumeInfo
    return (
...
```
状況に応じて使い分けてみてください。

shioさんもコメントで言っていた、「冗長な記述になってるのが気になってました」というのは非常に重要な観点で素晴らしいなと思いました👏
その疑問や引っ掛かりを解決するための方法はないか？といった視点で学習を進めると、より効率的な記述方法や根幹的な部分への理解が深まるので大事にしてください！

2023-11-17 04:09 UTC, NBmaeda commented on booklog/src/App.tsx
> +              <div className="sub-info">
確認しました！
データの有無で最終的なHTMLがどう変わるか？という視点を常に持つと、こういった細かい漏れ等がなくなって良いと思います💡

2023-11-20 00:44 UTC, merged