【FE課題】Step4
NBshiozawa/dept_design_fe_work01 pull request #4
Opened 2024-01-30 11:41 UTC by NBshiozawa

## 内容
以下対応しました。

* step4 headerの読書時間タイマーを作成
* フォームのデザイン変更

## issue
newbeescoltd/nb_study_react#25

## 補足
ソース上にメモ残しておりますが、これで良いのか...？という感じです🥹
また、フォームですが、select側にstep3と同じスタイルを適用すると違和感がありましたので、デザインを少し変更し、focus時のoutline-colorを変更する形に修正しております🙇‍♀️

2024-01-31 02:42 UTC, NBmaeda requested changes
Step4の対応お疲れ様です👏
ほぼほぼ問題ないです、流石です🎉

ただ1点追加してほしい箇所があります。
最新のリポジトリをpullしてもらうとタイマー終了時に「読書タイマー 終了」とテキストが変化すると思います。
変数の値に応じたテキスト及びスタイルの変更を学んでほしいので、ここの箇所を実装してほしいです🙏

変更を考慮したアナウンスができておらずすみません🙇
お手数ですが、ご対応をお願いします！

2024-01-31 02:42 UTC, NBmaeda commented on booklog/src/components/Timer.tsx
> +    // Number型に変換（型エラーでNumber使用しましたがこれで良いのかの状態
ここに関しては問題ないと思います👍
MDNの[Number()](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number)の項を見てみると、以下のように記載されています。
> 関数として使用された場合、 Number(value) は文字列やその他の値を数値型に変換します。値が変換できない場合は、 [NaN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/NaN) を返します。

そのため、`selectRef.current?.value`の値の種類に関わらず`countTime`の型に合致する値が返ってくる形となります。(TypeScriptのnumber型は[NaNを含みます](https://typescriptbook.jp/reference/values-types-variables/number#nan))

本ファイル24行目の`countDown()`に目を移すと、`if (isStart && countTime > 0) `の場合のみ`setCountTime()`が実行されて`countTime`が更新されます。
`NaN`はこの条件式に当てはまらず`countTime`の更新もされないため、不用意にuseEffectが走る心配もありません。

より厳密な実装をするケースではもう少し処理をする必要があるかもしれませんが、今回の場合ここの実装は問題ないと思います！👏

2024-01-31 02:42 UTC, NBmaeda commented on booklog/src/components/Timer.tsx
> +  useEffect(() => {
useEffect内の実装、素晴らしいですね👏
簡潔にまとまっていますし、クリーンアップ関数もしっかり記載しているのでとても良いと思います。

2024-02-09 05:43 UTC, NBshiozawa commented on booklog/src/components/Timer.tsx
> +    // Number型に変換（型エラーでNumber使用しましたがこれで良いのかの状態
なるほどです！やり方問題なかったみたいで安心しました...😌
丁寧にご説明いただきありがとうございます！

2024-02-09 05:45 UTC, NBshiozawa commented
ご確認ありがとうございます！
タイマー終了時の挙動について抜けており失礼しました！
ビルドせずに確認していたようでした...🙏

修正しましたので、お手数ですがご確認よろしくお願いします。

1点、見本ではカウント0になった瞬間タイマー終了（残り00秒は表示されない）となっていたのですが、どう記述してよいかわからずでした...
そのため、今回の対応ではミリ秒までしっかりカウントしたあとでタイマー終了の表示となっております🙇‍♀️

2024-02-09 09:11 UTC, NBmaeda requested changes
お忙しい中対応ありがとうございます👏
基本的には問題なかったのですが、「読書タイマー 終了」の表示タイミング周りの件のコメントをさせてもらいました。

特にuseEffectに渡す関数等、わかりにくければお気軽にご質問ください！
後一歩となりますので引き続きよろしくお願いします💪

2024-02-09 09:11 UTC, NBmaeda commented on booklog/src/components/Timer.tsx
>    }, [countTime])
ここの処理ですが、僕なら以下のように書きます💡
コメントも記載しているので併せて確認して欲しいのですが、これであればタイマーの表示も意図通りになっているかと思います🤔

基本的にshioさんの実装を大きく崩してはいないつもりですが、クリーンアップ関数から`setIsEnd(false)`を除いている点について補足します。
これに関しては「タイマーを作動させたタイミング」で実行した方が良いと判断して、15行目の`handleClick`に移すことを想定しています。

```
useEffect(() => {
    // `isStart && `をまとめる形で、isStart=falseの場合はreturnで以降の処理を実施しない
    if (!isStart) return
    const countDown = setInterval(() => {
      // 「タイマー終了」の表示タイミングを調整 & 1つのif...else文にまとめる
      if (countTime - 1 > 0) {
        setCountTime(countTime - 1)
      } else {
        clearInterval(countDown)
        setIsStart(false)
        setIsEnd(true)
      }
    }, 1000)

    return () => {
      clearInterval(countDown)
    }
  }, [countTime])
```

2024-02-09 09:11 UTC, NBmaeda commented on booklog/src/components/Timer.tsx
>    const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
下の方のコメントにも書きましたが、`setIsEnd(false)`は「タイマーを作動させたタイミング」で実行した方が良いと思っています💡
そのため、この`handleClick`関数内で実行すると良いかなと思います。

2024-02-13 08:10 UTC, NBshiozawa commented on booklog/src/components/Timer.tsx
>    }, [countTime])
記述例ありがとうございます！
やりたかったことをスッキリとまとめていただいて、なるほど！となりました🙇‍♀️

```
if (!isStart) return
```

はじめ、初回レンダリング時にタイマー終了表示になってしまい、`setIsEnd(true)` の記述位置で悩んだりしていたのですが、こういった書き方があったのですね！
if...elseもはじめの記述に引っ張られて思い付かずでした...🫠

1点、初歩的なことかもしれないのですが...

```
if (countTime - 1 > 0) {
```

` countTime > 1 ` とはしない理由について、言語化できておらず、お手数ですが確認させていただけますと幸いです🙏

2024-02-13 08:12 UTC, NBshiozawa commented
ご確認ありがとうございます！
フィードバックいただいた内容、修正いたしました。
お手数ですが、ご確認よろしくお願いします🙇‍♀️
（理解するため、自分の言葉でコメント記述しています）

また、1点確認させていただきたく、上のコメントに返信しておりますので併せてご確認いただけますと幸いです🙏

2024-02-13 09:41 UTC, NBmaeda commented on booklog/src/components/Timer.tsx
>    }, [countTime])
参考になったようで良かったです！
`if (!isStart) return`のような書き方は**早期リターン**といいます。
if...elseのネストを減らす際によく使われるもので、[この記事](https://zenn.dev/media_engine/articles/early_return)にまとめられているのでよければ見てみてください💡

--- 

> countTime > 1 とはしない理由について、言語化できておらず、お手数ですが確認させていただけますと幸いです🙏

こちらですが`countTime > 1`でも問題ないです！
ただ今回の場合はカウントが0になった際にタイマーを停止したいため、本来は`countTime > 0`としたい箇所となります。
残り時間表示の調整のために`-1`を行うため、以下のような思考の跡を残すため個人的に`countTime - 1 > 0`と記載しました🤔
- あくまで閾値は1ではなく0である。
- 調整のため`-1`をせざるを得なかった。

別にこれは慣習でも何でもないので好みですが、意図が伝わるコードという観点でこういう記載をしています！
もし何かご意見などあればもらえると嬉しいです🙏

2024-02-13 10:00 UTC, NBmaeda approved these changes
問題ないと思います、Step4の対応お疲れ様でした🎉
初めはuseEffectの書き方は慣れないと思いますが、徐々に理解していってもらえたらと思います💡
次のStepも少しややこしいですが、ここを終えると1つ山は抜けると思います！
引き続きサポートしますので頑張っていきましょう💪

2024-02-14 12:37 UTC, merged