【FE課題】Step5
NBshiozawa/dept_design_fe_work01 pull request #5
Opened 2024-02-28 11:15 UTC by NBshiozawa

## 内容
APIの連携を行い、検索結果をブックリストに反映できるようにする

## issue
newbeescoltd/nb_study_react#26

## 補足
型の書き方や、何をどこに記述すれば良いかなど迷走しておりました...
書き方があまり良くない、など何でもご指摘いただけますとありがたいです！
1箇所、ESLintのエラーの対処方法がまったくわからずでしたので、そのままになっております🙇‍♀️

2024-02-29 10:23 UTC, NBmaeda requested changes
Step5の対応お疲れ様です！👏
慣れないFetch APIの使用は難しかったと思います。

実装内容は概ね問題なかったのですが、+αな部分やエラーの解決のためのコメントをしております。
fetchの部分を簡略化して書くのが難しく、かなり分量が多くなってしまって申し訳ないです🙇

不明点や追加の説明・リソースが必要ならいつでも声かけてください🙏

2024-02-29 10:23 UTC, NBmaeda commented on booklog/src/components/Content.tsx
> +}
型の定義ですが、今回のようにAPIを使用するのであればドキュメントで確認することができます💡https://developers.google.com/books/docs/v1/using?hl=ja#response

関数`bookData`の中で`console.log(data)`してブラウザで確認すると、キーワードがヒットしない場合は`"kind", "totalItems"`のみ返ってくるようです。
そのため`items`をoptionalとして以下のようにするのが良いと思います。
```
type Result = {
  items?: BookItem[]
  kind: string
  totalItems: number
}
```

2024-02-29 10:23 UTC, NBmaeda commented on booklog/src/components/Content.tsx
> +  }
データの`fetch`部分は本stepのキモだと思います。
`bookItem`と`total`は`useState`で管理してくれているので、ページ更新の大体の流れは以下になると思います。
1. submitによってAPIにクエリを投げる。
2. `Promise`によってAPIからのレスポンスをキャッチ。
3. APIから返ってきたデータを`setState`でstateにセット。
4. stateの変更を検知して、React側がページの再レンダリング。

この箇所では上記の流れの`2`までやる形になると思います。
その上で2点考えると良いかなと思うことがあります。
### A. 関数名を`bookData`ではなく`fetchBookData`などにし、関数の役割を明確にする。
この場合アロー関数で定義している関数に、`bookData`という名前を与える形になっています。
`bookData`というと変数のように捉えられやすいため、`fetchBookData`とすることで関数であることが明確になります。

### B. `then`メソッドを使用する。
この関数の戻り値は`Promise<BookData>`なので、「`BookData`型の戻り値を戻す、`Promise`オブジェクトを戻す」という感じです。
何が何だかですね🤯

一旦先に進みます。`fetch`に関する[このドキュメント](https://developer.mozilla.org/ja/docs/Web/API/fetch#%E4%BE%8B)を見てみてください。
`fetch`メソッドは前提として、`Promise`を戻り値として持ちます。
その`Promise` の`then`と`catch`というメソッドを使って、`fetch().then().them().catch()`のようなチェーンの形で処理を書くことができます。
例えば先のドキュメントの例をちょっと変えると以下のように書けます。
```
fetch(myRequest)
  .then((response) => {
    if (!response.ok) {
      throw new Error(`HTTP error! Status: ${response.status}`);
    }

    return response.blob();
  })
  .then((response) => {
    myImage.src = URL.createObjectURL(response);
  }).
  .catch((error) => {
    console.error(error);
  });
```

- `then`メソッドは、直前の`fetch`メソッドあるいは`then`メソッドの「戻り値」を引数として受け取ることができます。この「戻り値」は実際には`Promise`に包まれた形なので、便宜的に括弧書きします。
  - 1つ目の`then`の場合、`fetch(myRequest)`の「戻り値」を`response`という引数に格納しています。
  - 「`BookData`型の戻り値を戻す、`Promise`を戻す」というのは、「次の`then`で受け取れるデータの型が`BookData`型である、`Promise`を戻す」という感じです。なんとなく理解できたでしょうか？🤔
- `then`メソッド内で`Error`が`throw`されると、`throw`以降の処理は無視してすぐさま`catch`メソッド内の処理に移ります。
  - 上記の場合は、最初の`then`で`!response.ok`であった場合、すぐさま`catch`メソッド内の`console.error(error)`が実行されます。
  - `then`と同様に、`catch`では`Error`オブジェクト自体を引数`error`で受け取ることができます。

というのがざっくりとした説明になります。
結局この関数で何をするかですが、shioさんがすでにやっていることを`then`メソッドを使って書き換えて、エラー処理を追加するという感じです。
まとめると以下のような形になります。
- `then`メソッドを使い、`!response.ok`の場合に`Error`を`throw`するようにする。
- `then`メソッドをつなげて、最後の`then`内で`BookData`で型アサーションされた`data`を`return`する。

つまり、shioさんがすでにやっていることを`then`メソッドを使って書き換えて、エラー処理を追加するという感じです。
一応[この記事](https://zenn.dev/junki555/articles/4ab67fc78ce64c)に参考になるドキュメントも含めてまとめられているのですが、かなり難しいと思うのでいつでも気軽にご質問ください🙏

2024-02-29 10:23 UTC, NBmaeda commented on booklog/src/components/Content.tsx
> +
前提として、`async`は外してもらって大丈夫です。59行目のエラーはこの`async`が原因となっています。
`onSubmit`で受け取る関数の戻り値は`void`である必要があるのですが、`async`キーワードをつけることで戻り値が`Promise<void>`となってしまうことが原因です。

さてこの関数ないで行う処理ですが、先の`fetchBookData`を使用して、`then`でチェーンを続けていく形になります。
具体的には以下のように書いていきます。
```
...
    e.preventDefault()
    if (inputRef.current?.value === '') return

    fetchBookData()
        .then(data => {
            // dataで受け取った値をそれぞれ bookItem と total に格納する処理。
        })
        .catch(error => {
            // fetchBookData で throw したエラーを出力する処理。
        })
}
```
具体的な処理に関しては書いていないのですが、わかりそうでしょうか？🤔
不明点等あれば聞いてください！！

2024-02-29 10:23 UTC, NBmaeda commented on booklog/src/components/SearchForm.tsx
> +export const SearchForm = forwardRef<HTMLInputElement, Props>(({ onSubmit }, ref) => {
`forwardRef`の使用、素晴らしいです👏
UIコンポーネントライブラリを作る時は結構使うので、ぜひ覚えておいてください。

2024-03-05 04:11 UTC, NBshiozawa commented on booklog/src/components/Content.tsx
> +  }
大変丁寧に解説していただき、ありがとうございます🙏
いただいた内容を元に、以下を修正してみました。

> * thenメソッドを使い、!response.okの場合にErrorをthrowするようにする。
> * thenメソッドをつなげて、最後のthen内でBookDataで型アサーションされたdataをreturnする。

一行ずつ処理を整理していった関係でコメントだらけになっております🙇‍♀️
読みにくくなっておりすみませんが、ご確認よろしくお願いいたします！

***

> 「BookData型の戻り値を戻す、Promiseオブジェクトを戻す」

```
fetchで取得した Response を JSON として解釈したものの型がBookData型となる。
fetch() や then() は Promiseオブジェクトを戻すため、fetchBookData の戻り値はBookData型のPromiseとなる
```
...ということでしょうか？

非同期まわりがだいぶ曖昧な状態でしたので、改めてご紹介いただいたドキュメントや[こちら](https://zenn.dev/estra/books/js-async-promise-chain-event-loop/viewer/f-epasync-asynchronous-apis)など読みつつ理解を試みたのですが、まだふわっとした状態です🥹
一旦、fetchメソッドについては以下のように自分の中で言語化してみたのですが、認識が間違っている点ご指摘いただけますと幸いです🙇‍♀️

```
fetch()は、Responseオブジェクトを結果に持つPromiseオブジェクトを戻す。
Responseは HTTP レスポンス全体を表現するものとなりそのままでは使えないため、
json()メソッドで本体のテキストを JSON として抽出する必要がある（json以外もある）

また、fetch() は非同期APIとなるため、処理結果を使って何かをする際の実行タイミングがずれる。
そのためPromiseでラップしたオブジェクトを返して状態を監視しつつ、
処理結果がわかったら then()に結果を引数として渡して次の処理を行う。
```

2024-03-05 04:15 UTC, NBshiozawa commented on booklog/src/components/Content.tsx
> +
ありがとうございます！
`async/await` がしっかり理解できておらずでした...🙏
`fetchBookData`を使用して、`then`でチェーンを続けていく形で修正してみましたので、お手数ですがご確認よろしくお願いいたします🙇‍♀️

2024-03-05 04:19 UTC, NBshiozawa commented
ご確認と、とても丁寧な解説ありがとうございます！
なんとか修正してみましたので、お手数ですがご確認よろしくお願いします🙏

step5ははじめに `async/await` を使うのかな？とこちらをベースに調べてしまったのですが、まずは`Promise`まわりを理解する必要があるのですね🥹
まだまだ理解がふんわりしているので、引き続き学習頑張ります！

2024-03-05 07:27 UTC, NBmaeda commented on booklog/src/components/Content.tsx
> +  }
```
fetchで取得した Response を JSON として解釈したものの型がBookData型となる。
fetch() や then() は Promiseオブジェクトを戻すため、fetchBookData の戻り値はBookData型のPromiseとなる
```
```
fetch()は、Responseオブジェクトを結果に持つPromiseオブジェクトを戻す。
Responseは HTTP レスポンス全体を表現するものとなりそのままでは使えないため、
json()メソッドで本体のテキストを JSON として抽出する必要がある（json以外もある）

また、fetch() は非同期APIとなるため、処理結果を使って何かをする際の実行タイミングがずれる。
そのためPromiseでラップしたオブジェクトを返して状態を監視しつつ、
処理結果がわかったら then()に結果を引数として渡して次の処理を行う。
```

両方とも上記の認識で良いと思います👏
しっかりドキュメント等を読み込んで、そこまで言語化できるのは素晴らしいと思います🎉

ちなみに記載いただいたzennの記事、かなり勉強になりますね！
僕も理解できていない部分がクリアになったので非常にありがたいです🙇

2024-03-05 08:32 UTC, NBmaeda approved these changes
Step5の対応お疲れ様でした！
とても良いと思います🎉

JSX内の検索ヒット数に応じた条件分岐などもしっかり考慮されていて素晴らしいです。
またAPIの仕様等に踏み込んでしっかり調べる姿勢は流石だなと感心しました👏
その学習の仕方はかなりの強みだと思うので、是非続けていってほしいです。

次のStepは比較的軽めだとは思うので、コンポーネントの分割を意識してみてください！
ゴールも見えてきたので残りも頑張っていきましょう💪

2024-03-05 08:32 UTC, NBmaeda commented on booklog/src/components/Content.tsx
> +        // bookItem を set（ヒットしない場合は空の配列をsetする...？）
この書き方で問題ないと思います👍

2024-03-05 08:32 UTC, NBmaeda commented on booklog/src/components/Content.tsx
> +    console.log(fetchBookData())
`console.log()`の中に`関数名()`を書くと、その行の時点で関数が実行されて`return`されたものがコンソールに表示されるという状態になります。

```
console.log(fetchBookData());
```

そのため上記のように書いてしまうと、45行目の`fetchBookData()`とは別に2回目の`fetchBookData()`が呼び出され、その結果として未解決の`Promise`が返されるため`Promise {<pending>}`が出力されている状態かと思います💡
もしデータフェッチの流れを段階を追って確認したければ、`then()`メソッド内にそれぞれ`console.log(response)`, `console.log(data)`のように引数をそのまま出力する形の処理を書くと良いかもしれません🤔

2024-03-05 11:18 UTC, merged