【FE課題】Step6
NBshiozawa/dept_design_fe_work01 pull request #6
Opened 2024-03-12 01:38 UTC by NBshiozawa

## 内容

モックデータを使用して、Mybooksのリストを作成

## issue

newbeescoltd/nb_study_react#27

## 補足
ファイルが増えてきたため、ディレクトリを見直しております。
変更ファイルが多くなってしまいすみませんが、ご確認よろしくお願いします🙏

2024-03-13 01:51 UTC, NBmaeda requested changes
Step6の対応お疲れ様です！
コンポーネントの分割とディレクトリ構成の変更をAtomicDesignに沿ってガッツリ行っていただいてありがとうございます👏
コンポーネントのカテゴリ分け(atoms, molecules等)も分かりやすくできていますし、各コンポーネントの粒度も丁度良いのではないかと思います。

2点だけ、細かい部分でFBさせてもらいました！
あと一歩で本Step完了という感じなので、よろしくお願いします🙏

2024-03-13 01:51 UTC, NBmaeda commented on booklog/src/components/atoms/BookImage.tsx
> +      )}
三項演算子を利用して条件分岐できていて良いですね👏
分割の粒度も適当で、ファイル全体としても簡潔にまとまっていて良いと思います。

2024-03-13 01:51 UTC, NBmaeda commented on booklog/src/components/atoms/BookPreviewLink.tsx
> +      <a className={styles.previewLink} href={previewLink} target="_blank">
本コンポーネントだけで見るのであれば、`previewLink`の型が`string | undefined`なので`previewLink===undefined`の場合は`null`を返す等にすると良いと思います。
そうしないと`href`属性が存在しない`a`要素が爆誕してしまいます。

あるいは親コンポーネントの中で条件分岐を行っているので、本コンポーネントの`Props`で`previewLink: string`にしてあげるでも良いと思います。
そうすることで`previewLink===undefined`の場合はエディタがエラーを出力してくれるため、`href`属性が存在しない`a`要素が出力されるのを未然に防いでくれます。

まとめると1つ目の方法はエラー処理を子コンポーネントで担う形、2つ目の方法は親コンポーネントでのエラー処理を強制する形になっています。
このように、コンポーネントの中身を知らなくても安全に使える状態というのが1つの理想系だと思うので、参考にしてもらえると幸いです💡

2024-03-13 01:51 UTC, NBmaeda commented on booklog/src/components/atoms/BookSubInfo.tsx
このファイルも`BookPreviewLink.tsx`と同じくですね💡
ただこの場合2つ目の方法での書き方の強制は難しいと思うので、1つ目の方法を取るのが良いと思います。
それにより不要な`div`タグの出力を防ぐことができます。

2024-03-14 10:09 UTC, NBshiozawa commented
ご確認ありがとうございます！
書き方は統一したいな...と個人的に思いましたので、どちらのコンポーネントも1つ目に挙げていただいたエラー処理を追加する形で修正いたしました🙇‍♀️
お手数ですが、ご確認よろしくお願いします🙏

2024-03-15 03:38 UTC, NBmaeda approved these changes
Step6の対応お疲れ様です🎉
概ね問題ないと思います！Approveしました🥳

1点気になる点をコメントしましたので、参考にしてみてください！
細かい点にはなりますが、規模の大きなアプリケーションになればなるほど気にすべき点かと思うので、頭に入れておいてもらえればと思います。

2024-03-15 03:38 UTC, NBmaeda commented on booklog/src/components/atoms/BookPreviewLink.tsx
> +      )}
処理の意図的には問題ないと思います！👏
ただ僕なら以下のようにすると思います。

```
export const BookPreviewLink = ({ previewLink }: Props): JSX.Element | null => {
  if (typeof previewLink !== 'string') return null
  return (
    <a className={styles.previewLink} href={previewLink} target="_blank">
      詳しく見る
    </a>
  )
}
```

違いとしては
- `previewLink`が`string`型でない場合は`null`を返し、[fragment](https://ja.react.dev/reference/react/Fragment)(`<></>`)も返さない。
- `previewLink`が`string`型の場合は、`a`要素のみを返す。

shioさんの実装でも問題はないのですが、細かいことを言うと`previewLink`の値によらずfragmentを返す実装になっています。
軽微な違いにはなりますが多少なりともパフォーマンスに影響があるため、出来たら避けた方が良いかなと個人的には思っています🤔

詳しい内容が書かれている記事を見つけたので、良ければあわせて読んでみてください🤲
https://b.0218.jp/202308312246.html

2024-03-15 07:34 UTC, merged